app:
  serviceUrl: "http://localhost:8080"
kafka:
  brokers:
   - localhost:9091
  topic: events
  consumerGroupId: AAAA
smtp:
  server: localhost
  port: 12333
  login: "maillogin"
  password: "mailpass"
  email: "coworker@example.com"