// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: shortlinks.proto

package shortlinks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shortlinks_Create_FullMethodName = "/shortlinks.Shortlinks/Create"
)

// ShortlinksClient is the client API for Shortlinks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortlinksClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type shortlinksClient struct {
	cc grpc.ClientConnInterface
}

func NewShortlinksClient(cc grpc.ClientConnInterface) ShortlinksClient {
	return &shortlinksClient{cc}
}

func (c *shortlinksClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Shortlinks_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortlinksServer is the server API for Shortlinks service.
// All implementations must embed UnimplementedShortlinksServer
// for forward compatibility.
type ShortlinksServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedShortlinksServer()
}

// UnimplementedShortlinksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortlinksServer struct{}

func (UnimplementedShortlinksServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShortlinksServer) mustEmbedUnimplementedShortlinksServer() {}
func (UnimplementedShortlinksServer) testEmbeddedByValue()                    {}

// UnsafeShortlinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortlinksServer will
// result in compilation errors.
type UnsafeShortlinksServer interface {
	mustEmbedUnimplementedShortlinksServer()
}

func RegisterShortlinksServer(s grpc.ServiceRegistrar, srv ShortlinksServer) {
	// If the following call pancis, it indicates UnimplementedShortlinksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shortlinks_ServiceDesc, srv)
}

func _Shortlinks_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortlinksServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortlinks_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortlinksServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shortlinks_ServiceDesc is the grpc.ServiceDesc for Shortlinks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shortlinks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortlinks.Shortlinks",
	HandlerType: (*ShortlinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shortlinks_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shortlinks.proto",
}
