app:
  serviceUrl: "http://localhost:8080"
kafka:
  brokers:
   - localhost:9091
  topic: events
  consumerGroupId: notifyer-group
smtp:
  server: localhost
  port: 12333
  login: "maillogin"
  password: "mailpass"
  email: "notifyer@example.com"